config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :banks, :providers

  root to: 'dashboard#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_one :bank

  validates :phone, length: { maximum: 10 }
  validates :b_account, length: { maximum: 15 }
  validates :nit, format: { with: /\d\d\d\d\d\d\d\d\d-\d/, message: "debe tener la forma xxxxxxxxx-x" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout :layout_by_resource

  private

  def layout_by_resource
    if user_signed_in?
      "application"
    else
      "devise"
    end
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumb

  def index
    @banks = Bank.all.page(params[:page]).per(10)
    @aria_banks = ' bg-gray-900 text-white'
  end

  def new
    @bank = Bank.new
  end

  def edit
  end

  def show
  end

  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html {redirect_to banks_path, notice: 'Banco creado'}
      else
        format.json {render json: @bank.errors.full_messages, status: :unprocessable_entity}
        format.js {render new}
      end
    end
  end

  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html {redirect_to banks_path, notice: 'Banco modificado'}
      else
        format.json { render json: @bank.errors.full_messages, status: :unprocessable_entity }
        format.js { render edit }
      end
    end
  end

  def destroy
    @bank.destroy
    respond_to do |format|
      format.html {redirect_to banks_path, notice: 'Banco eliminado'}
    end
  end

  private

  def set_bank
    @bank = Bank.find(params[:id])
  end

  def set_breadcrumb
    @breadcrumb_top = "Bancos"
  end

  def bank_params
    params.require(:bank).permit(:name)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @aria_index = ' bg-gray-900 text-white'
    @breadcrumb_top = "Dashboard"
    @banks = Bank.count
    @providers = Provider.count
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumb
  before_action :set_banks, only: [:new, :edit, :show, :create, :update]

  def index
    @providers = Provider.all.page(params[:page]).per(10)
    @aria_providers = ' bg-gray-900 text-white'
  end

  def new
    @provider = Provider.new
  end

  def edit
  end

  def show
    @bank_name = Bank.find_by id: @provider.bank_id
  end

  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html {redirect_to providers_path, notice: 'Proveedor creado'}
      else
        format.html { render :new }
        format.json { render json: @provider.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html {redirect_to providers_path, notice: 'Proveedor modificado'}
      else
        format.html { render :edit }
        format.json { render json: @provider.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_path, notice: 'Proveedor eliminado' }
    end
  end

  private

  def set_provider
    @provider = Provider.find(params[:id])
  end

  def set_banks
    @banks_select = Bank.all.map{|bank| [bank.name, bank.id] }
  end

  def set_breadcrumb
    @breadcrumb_top = "Proveedores"
  end

  def provider_params
    params.require(:provider).permit(:name, :nit, :contact, :phone, :b_account, :bank_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/banks/_form.html.erb
<%= form_with model: @bank, data: {local: true}, class: '' do |form| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%#= pluralize(@bank.errors.count, "error") %> prohibited this declaracion_jurada from being
          saved:</h2>-->

      <ul>
        <% @bank.errors.full_messages.each do |message| %>
          <div class="bg-purple-100 rounded-lg py-5 px-6 mb-4 text-base text-purple-700 mb-3" role="alert">
            <%= message %>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label 'Nombre', class: "mt-3 form-label inline-block mb-2 text-gray-700 text-sm" %>
  <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white", placeholder:"nombre del banco", required: true %>
  <%= form.button @bank.new_record? ? "Guardar" : "Actualizar", type: 'submit', class: "mt-8 boton-modal-bank w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
<% end %>

app/views/banks/_modal.html.erb
<!-- Main modal -->
<div class="modal fade fixed top-0 left-0 hidden w-full h-full outline-none overflow-x-hidden overflow-y-auto"
     id="modalBank" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog relative w-auto pointer-events-none">
    <div
      class="modal-content border-none shadow-lg relative flex flex-col w-full pointer-events-auto bg-white bg-clip-padding rounded-md outline-none text-current">
      <div
        class="modal-header flex flex-shrink-0 items-center justify-between p-4 border-b border-gray-200 rounded-t-md">
        <h5 class="text-xl font-medium leading-normal text-gray-800" id="modal-bank-title"></h5>
        <button type="button"
                class="btn-close box-content w-4 h-4 p-1 text-black border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-black hover:opacity-75 hover:no-underline"
                data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body relative p-4">
        <div class="modal-body-bank" id="modal-body-bank"></div>
      </div>

    </div>
  </div>
</div>

app/views/banks/edit.js.erb
// Add the dialog title
$('#modal-bank-title').html('Modificar banco');

// Render the new form
$('.modal-body-bank').html('<%= j render("form") %>');

// Show the dynamic dialog // Set Focus to the first element
$(function(){
   $('#modalBank').on('shown.bs.modal', function(){
      $(this).find('#bank_name').focus();
   });
});

app/views/banks/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center">
          <thead class="border-b bg-gray-800">
          <tr>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Nombre
            </th>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Opciones
            </th>
          </tr>
          </thead>
          <tbody>
          <% @banks.each do |bank| %>
            <tr class="bg-white border-b border-gray-300" id="bank_<%= bank.id %>">
              <td class="text-sm text-gray-900 font-light px-6 py-2 whitespace-nowrap">
                <%= bank.name %>
              </td>
              <td class="py-4 px-6">
                <%= link_to edit_bank_path(bank), remote: true, data: {'bs-toggle': 'modal', 'bs-target': '#modalBank'}, class: 'inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out' do %>
                  <i class="fas fa-pen"></i>
                <% end %>
                <%= link_to bank, method: :delete, data: {confirm: "vas a eliminar #{bank.name}"}, class: 'inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%= paginate @banks, outer_window: 3 %>
      </div>
    </div>
  </div>
</div>

app/views/banks/new.js.erb
// Add the dialog title
$('#modal-bank-title').html('Nuevo banco');

// Render the new form
$('.modal-body-bank').html('<%= j render("form") %>');

// Show the dynamic dialog // Set Focus to the first element
$(function(){
   $('#modalBank').on('shown.bs.modal', function(){
      $(this).find('#bank_name').focus();
   });
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
<head>
  <title>Prueba</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css"/>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="h-full">
<main>
  <div class="min-h-full">
    <nav class="bg-gray-800">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
            </div>
            <div class="hidden md:block">
              <div class="ml-10 flex items-baseline space-x-4">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <%= link_to 'Dashboard', root_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium #{@aria_index}", aria: { current: "page" }, data: { turbolinks: " false" } %>

                <%= link_to 'Bancos', banks_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium #{@aria_banks}", data: { turbolinks: "false" } %>

                <%= link_to 'Proveedores', providers_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium #{@aria_providers}", data: { turbolinks: "false" } %>

              </div>
            </div>
          </div>
          <div class="hidden md:block">
            <div class="ml-4 flex items-center md:ml-6">

              <!-- Profile dropdown -->
              <div class="relative ml-3">
                <div class="dropdown">
                  <button type="button" id="dropdownmenu1" data-bs-toggle="dropdown" aria-expanded="false" class="dropdown-toggle flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                    <span class="sr-only">Open user menu</span>
                    <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                  </button>


                  <!--
                    Dropdown menu, show/hide based on menu state.

                    Entering: "transition ease-out duration-100"
                      From: "transform opacity-0 scale-95"
                      To: "transform opacity-100 scale-100"
                    Leaving: "transition ease-in duration-75"
                      From: "transform opacity-100 scale-100"
                      To: "transform opacity-0 scale-95"
                  -->
                  <ul aria-labelledby="dropdownmenu1" class="dropdown-menu hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                    <!-- Active: "bg-gray-100", Not Active: "" -->
                    <li>
                      <%= link_to 'Editar perfil', edit_user_registration_path, class: 'dropdown-item block px-4 py-2 text-sm text-gray-700', data: {turbolinks: 'false'} %>
                    <li>
                    <li>
                      <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item block px-4 py-2 text-sm text-gray-700', data: {turbolinks: 'false'} %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="-mr-2 flex md:hidden menu-mobile">
            <div class="dropdown">
              <!-- Mobile menu button -->
              <button type="button" id="dropdownmenu2" data-bs-toggle="dropdown" aria-expanded="false" class="dropdown-toggle inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <!--
                  Heroicon name: outline/bars-3

                  Menu open: "hidden", Menu closed: "block"
                -->
                <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"/>
                </svg>
                <!--
                  Heroicon name: outline/x-mark

                  Menu open: "block", Menu closed: "hidden"
                -->
                <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                </svg>
              </button>

              <ul aria-labelledby="dropdownmenu2" class="dropdown-menu hidden md:hidden space-y-1 px-2 pt-2 pb-3 sm:px-3">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <li><%= link_to 'Dashboard', root_path, class: "dropdown-item text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium #{@aria_index}", aria: { current: "page" }, data: { turbolinks: "false" } %></li>

                <li><%= link_to 'Bancos', banks_path, class: "dropdown-item text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium #{@aria_banks}", data: { turbolinks: "false" } %></li>

                <li><%= link_to 'Proveedores', providers_path, class: "dropdown-item text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium #{@aria_providers}", data: { turbolinks: "false" } %></li>

              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="md:hidden menu-user-mobile">

        <div class="border-t border-gray-700">
          <div class="dropdown">
            <div class="flex items-center px-5">
              <div class="flex-shrink-0">
                <button id="dropdownmenu3" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false" class="dropdown-toggle mobile-user-button">
                  <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </button>
                <ul aria-labelledby="dropdownmenu3" class="dropdown-menu hidden md:hidden mt-3 space-y-1 px-2 pt-4 pb-3">

                  <li>
                    <%= link_to 'Editar perfil', edit_user_registration_path, class: 'dropdown-item block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white', data: {turbolinks: 'false'} %>
                  <li>
                  <li>
                    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white', data: {turbolinks: 'false'} %>
                  </li>
                </ul>
              </div>

            </div>

          </div>
        </div>
      </div>
    </nav>

    <header class="bg-white shadow">
      <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8 relative">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900"><%= @breadcrumb_top %></h1>
        <% unless controller_name == 'dashboard' %>
          <% if controller_name == 'banks' %>
            <%= link_to new_bank_path, remote: true, class: "new_button text-white text-sm bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 shadow-lg shadow-purple-500/50 dark:shadow-lg dark:shadow-purple-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2", id: 'nuevo-banco-btn', data: { 'bs-toggle': "modal", 'bs-target': "#modalBank" } do %>
              <i class="fas fa-plus"></i> Agregar nuevo
            <% end %>
          <% end %>
          <% if controller_name == 'providers' %>
            <%= link_to new_provider_path, class: "new_button text-white text-sm bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 shadow-lg shadow-purple-500/50 dark:shadow-lg dark:shadow-purple-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" do %>
              <i class="fas fa-plus"></i> Agregar nuevo
            <% end %>
          <% end %>
        <% end %>
      </div>
    </header>
    <main>
      <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
        <!-- Replace with your content -->
        <div class="px-4 py-6 sm:px-0">
          <% unless flash.empty? %>
            <div id="toast-simple" class="mb-3 flex items-center p-4 space-x-4 w-full max-w-xs text-gray-500 bg-white rounded-lg divide-x divide-gray-200 shadow dark:text-gray-400 dark:divide-gray-700 space-x dark:bg-gray-800" role="alert">
              <div class="pl-4 text-sm font-normal">
                <% flash.each do |type, msg| %>
                  <%= msg %>
                <% end %>
              </div>
            </div>
          <% end %>

          <%= yield %>
        </div>
        <!-- /End replace -->
      </div>
    </main>
  </div>

</main>

<%= render 'banks/modal' if controller_name == 'banks' %>

<!--<script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>-->
<script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>

</body>
</html>

app/views/providers/edit.html.erb
<div class="flex justify-center">
  <div class="block p-6 rounded-lg shadow-lg bg-white max-w-sm">
    <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2">Modificar proveedor</h5>
    <%= render 'form' %>
  </div>
</div>

app/views/providers/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center">
          <thead class="border-b bg-gray-800">
          <tr>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Nombre
            </th>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Contacto
            </th>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Teléfono
            </th>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Banco
            </th>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Cuenta
            </th>
            <th scope="col" class="text-white text-sm font-medium text-gray-900 px-6 py-2">
              Opciones
            </th>
          </tr>
          </thead>
          <tbody>
          <% @providers.each do |provider| %>
            <tr class="bg-white border-b border-gray-300" id="bank_<%= provider.id %>">
              <td class="text-sm text-gray-900 font-light px-6 py-2 whitespace-nowrap">
                <%= provider.name.present? ? provider.name : "Sin información en la tabla" %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-2 whitespace-nowrap">
                <%= provider.contact.present? ? provider.contact : "Sin información en la tabla" %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-2 whitespace-nowrap">
                <%= provider.phone.present? ? provider.phone : "Sin información en la tabla" %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-2 whitespace-nowrap">
                <%= Bank.find_by(id: provider.bank_id).name %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-2 whitespace-nowrap">
                <%= provider.b_account.present? ? provider.b_account : "Sin información en la tabla" %>
              </td>
              <td class="py-4 px-6">
                <%= link_to provider_path(provider), class: 'inline-block px-6 py-2.5 bg-green-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out' do %>
                  <i class="fas fa-eye"></i>
                <% end %>
                <%= link_to edit_provider_path(provider), class: 'inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out' do %>
                  <i class="fas fa-pen"></i>
                <% end %>
                <%= link_to provider, method: :delete, data: {confirm: "vas a eliminar #{provider.name}"}, class: 'inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%= paginate @providers, outer_window: 3 %>
      </div>
    </div>
  </div>
</div>

app/views/providers/show.html.erb
<div class="flex justify-center">
  <div class="block rounded-lg shadow-lg bg-white max-w-sm text-center">
    <div class="py-3 px-6 border-b border-gray-300">
      <div>
        <%= link_to edit_provider_path(@provider), class: 'inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out' do %>
          <i class="fas fa-pen"></i>
        <% end %>
        <%= link_to @provider, method: :delete, data: {confirm: "vas a eliminar #{@provider.name}"}, class: 'inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out' do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
    <div class="p-6">
      <h5 class="text-gray-900 text-xl font-medium mb-2"><%= @provider.name %></h5>
      <p class="text-gray-700 text-base mb-4">
        NIT: <%= @provider.nit %> <br>
        Contacto: <%= @provider.contact %> <br>
        Teléfono: <%= @provider.phone %> <br>
        Banco: <%= @bank_name.name %> <br>
        Cuenta: <%= @provider.b_account %>
      </p>
    </div>
    <div class="py-3 px-6 border-t border-gray-300 text-gray-600">
      <%= link_to 'Volver', providers_path, class: 'inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out' %>
    </div>
  </div>
</div>